language: c # not actually used, but lua is not an option
sudo: require
python: "3.6"

addons:
  apt:
    packages:
      - lua
      - lua-ldoc

before_deploy:
  # run the docs
  - cd docs
  - python3 generate_docs.py
  # file to tell GitHub pages not to try to run jekyll stuff (can break urls)
  - touch output/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/output
  github-token: $GH_TOKEN
  on:
    branch: master
