language: c # not used
python: "3.6.3"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lua5.1 lua-ldoc python3-pip

script:
  - echo "do nothing"

before_deploy:
  # run the docs
  - cd docs
  - pip3 install --user -r requirements.txt
  - python3 generate_docs.py
  # file to tell GitHub pages not to try to run jekyll stuff (can break urls)
  - touch output/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/output
  github-token: $GH_TOKEN
  on:
    branch: master
